name: Subgraph CI/CD

on:
  pull_request:
    branches: [main]
    paths: ['pop-subgraph/**']
  push:
    branches: [main]
    paths: ['pop-subgraph/**']

jobs:
  subgraph:
    uses: BreadchainCoop/subgraphform/.github/workflows/_subgraph-cicd.yml@main
    with:
      subgraph-name: poa-2
      working-directory: pop-subgraph
    secrets:
      GRAPH_DEPLOY_KEY: ${{ secrets.GRAPH_DEPLOY_KEY }}
